name: docker-pull

on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: |
          for module in containers/*; do
            if [ -f "$module"/Dockerfile ]; then
              image="alexthiery/${module##*/}:latest"
              printf "Pulling %s\n" "$image"
              docker pull "$image"
            fi
          done