name: docker-pull

on:
  push:
    branches: 
      - main
  # schedule:
  #   - cron: 0 0 3 * *

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: |
          lastrepo=""
          lastseen=""
          images=()

          for module in containers/*; do
              if [ -f "$module"/Dockerfile ]; then
                  images+=($(echo "alexthiery/${module##*/}:latest))
              fi
          done

          for image in "${images[@]}"; do
              # Parse repository name, we will remove the previous image if different
              readarray -d : -t repository <<< "$image"
              if [ "${lastseen}" != "" ] && [ "${repository[0]}" != "${lastseen}" ]; then
                  printf "Removing image ${lastseen} to make room."
                  docker rmi "${lastrepo}" || docker rmi "${lastseen}"
              fi
              lastrepo="${repository[0]}"
              lastseen="${image}"
              printf "Pulling $image\n";
              docker pull "${image}"
          done
